# 参考文档：https://doc.rust-lang.org/cargo/reference/config.html

[build]
target = "leios_x86_64.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
